### ISSUE TITLE
Implementing has_email function

### ISSUE THREAD

**Issue by kaylaqhenry** [NCATComp410/comp410_spring_2022#76]
(words/numbers)@domain.com

**Comment by claesmk** [comment]
Here are some requirements for you:

1. Per RFC3696, the name part of an email address has some minor restrictions, such as that a dot "." cannot be the last character of the name.
2. Per RFC3696, any ASCII character may be part of the name as long as it is escaped with a backslash.  I don't recommend supporting this since it is rarely, if ever, used in practice
